#!/usr/bin/env perl

use v5.12;

use FindBin qw($Bin);
use lib "$Bin/lib";
use Getopt::Long;

@ARGV = ('--shell') unless @ARGV;

my $shell;
my $eval = '';

GetOptions (
    "shell" => \$shell,
    "eval=s" => \$eval,
) or die("Error in command line arguments\n");

require REPL;

if ($eval) {
    if ($shell) {
        REPL::rep(qq<(do $eval)>);
    } else {
        REPL::rep(qq<(prn (do $eval))>);
    }
} elsif (@ARGV) {
    my $file = shift;
    -f $file or die "No such file '$file'";
    REPL::rep(qq<(load-file "$file")>);
}

REPL->repl if $shell;
