SOURCES_BASE = readline.l reader.l printer.l types.l
SOURCES_LISP = env.l func.l core.l stepA_mal.l
SOURCES = $(SOURCES_BASE) $(SOURCES_LISP)

all:

clean:

.PHONY: stats tests $(TESTS)

stats: $(SOURCES)
	@wc $^
	@printf "%5s %5s %5s %s\n" `grep -E "^[[:space:]]*#|^[[:space:]]*$$" $^ | wc` "[comments/blanks]"
stats-lisp: $(SOURCES_LISP)
	@wc $^
	@printf "%5s %5s %5s %s\n" `grep -E "^[[:space:]]*#|^[[:space:]]*$$" $^ | wc` "[comments/blanks]"

