#!/bin/bash
args=""
if [ "$#" -gt 0 ]; then
    args="'$1'"
    for a in "${@:2}"; do
        args="$args,'$a'"
    done
fi
if [ "$matlab_MODE" = "matlab" ] ; then
    exec matlab -nodisplay -nosplash -nodesktop -nojvm -r "${STEP:-stepA_mal}($args);quit;"
else
    exec octave -q --no-gui --no-history --eval "${STEP:-stepA_mal}($args);quit;"
fi
