src/step%:
	spago bundle-app --main ${${@F}} --to $(@F:%.purs=%.js)


#####################

step0_repl.purs = Mal.Step0
step1_read_print.purs = Mal.Step1
step2_eval.purs = Mal.Step2
step3_env.purs = Mal.Step3
