src/step%:
	spago bundle-app --main ${${@F}} --to $(@F:%.purs=%.js)


#####################

step0_repl.purs = Mal.Step0
step1_read_print.purs = Mal.Step1
step2_eval.purs = Mal.Step2
step3_env.purs = Mal.Step3
step4_if_fn_do.purs = Mal.Step4
step5_tco.purs = Mal.Step5
step6_file.purs = Mal.Step6
step7_quote.purs = Mal.Step7
