
TESTS =


SOURCES = src/main/java/mal/types.java src/main/java/mal/readline.java \
	  src/main/java/mal/reader.java src/main/java/mal/Env.java \
	  src/main/java/mal/step5_tco.java

#.PHONY: stats tests $(TESTS)
.PHONY: stats

stats: $(SOURCES)
	@wc $^

#tests: $(TESTS)
#
#$(TESTS):
#	@echo "Running $@"; \
#	python $@ || exit 1; \
