EOF=0

REM READLINE(A$) -> R$
READLINE:
  EOF=0
  PROMPT$=A$
  PRINT PROMPT$;
  CH$="": LINE$="": CH=0
  READCH:
    GET CH$: IF CH$="" THEN READCH
    CH=ASC(CH$)
    IF (CH=4 OR CH=0) THEN EOF=1: GOTO RL_DONE: REM EOF
    IF (CH=127) THEN GOSUB RL_BACKSPACE
    IF (CH=127) THEN GOTO READCH
    IF (CH<32 OR CH>127) AND CH<>13 THEN READCH
    IF LEN(LINE$)<255 AND CH$<>CHR$(13) THEN LINE$=LINE$+CH$
    IF LEN(LINE$)<255 AND CH$<>CHR$(13) THEN GOTO READCH
  RL_DONE:
    R$=LINE$
    RETURN

  REM Assumes LINE$ has input buffer
  RL_BACKSPACE:
  IF LEN(LINE$)=0 THEN RL_BACKSPACE_ONCE:
    PRINT CHR$(157) + CHR$(157) + "  " + CHR$(157) + CHR$(157);
    LINE$=LEFT$(LINE$, LEN(LINE$)-1)
    RETURN
  RL_BACKSPACE_ONCE:
    PRINT CHR$(157) + " " + CHR$(157);
    RETURN 
