STEPS = step0_repl.io step1_read_print.io step2_eval.io step3_env.io step4_if_fn_do.io step5_tco.io \
        step6_file.io step7_quote.io step8_macros.io step9_try.io stepA_mal.io

all: eerie

eerie:
	ln -s /opt/.eerie eerie

$(STEPS): eerie

clean:
