#!/bin/bash
cd $(dirname $0)
(echo "(def! -*ARGS*- (list $(for a in "${@}"; do echo -n " \"${a}\""; done)))") > .args.mal
case ${basic_MODE:-cbm} in
    cbm)    exec cbmbasic ${STEP:-stepA_mal}.bas "${@}" ;;
    qbasic) exec ./${STEP:-stepA_mal} "${@}" ;;
    *)      echo "Invalid basic_MODE: ${basic_MODE}"; exit 2 ;;
esac
