#!/bin/bash
case ${HAXE_MODE:-neko} in
    neko)   exec neko    $(dirname $0)/${STEP:-stepA_mal}.n   "${@}" ;;
    python) exec python3 $(dirname $0)/${STEP:-stepA_mal}.py  "${@}" ;;
    js)     exec node    $(dirname $0)/${STEP:-stepA_mal}.js  "${@}" ;;
    cpp)    exec         $(dirname $0)/cpp/${STEP:-stepA_mal} "${@}" ;;
    *) echo "Invalid HAXE_MODE: ${HAXE_MODE}"; exit 2 ;;
esac
