#!/usr/bin/env ruby

cmdline = ['chuck', '--caution-to-the-wind', '--silent']

# HACK: makes `make MAL_IMPL=chuck "test^mal"` work
scriptpath = File.expand_path(File.dirname(__FILE__))
Dir.chdir(scriptpath)

scriptfile = (ENV['STEP'] || 'stepA_mal') + '.ck'

script = File.readlines(scriptfile)
imports = script.grep(%r{^ *// *@import (.+)}) { $1 }
import_files = imports.flat_map { |i| Dir[i] }
cmdline += import_files
cmdline << scriptfile

File.write('/tmp/chuck-cmdline', cmdline.join(' '))
File.write('/tmp/chuck-args', ARGV.join(' '))

ENV['CHUCK_ARGS'] = ARGV.join("\a")
exec(*cmdline)
